[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    tzapu/WiFiManager @ ^2.0.17
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1

; Example for ESP32-S3
; [env:esp32s3]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino
; lib_deps =
;     bblanchon/ArduinoJson @ ^6.21.5
;     tzapu/WiFiManager @ ^2.0.17
