[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1

; For other boards e.g. ESP32-S3:
; [env:esp32-s3-devkitc-1]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino
; ... same lib_deps
